### ISSUE TITLE
Capture Headings from Generated Markdown

### ISSUE THREAD

**Issue by kenjioman** [ian-r-rose/jupyterlab-toc#15]
First off, thank you for a great extension!  Very useful to help organize long documents.  One area that this doesn't touch, however, is if one code-block outputs a lot of figures, tables, etc, and we would like to break it up into chunks.  This can be done with `IPython.display.Markdown` (as seen [in this link](https://stackoverflow.com/a/44098682)), but the toc extension is not currently capturing these headings.

So, a feature request:  Capture Headings displayed with `IPython.display.Markdown` as well, so you can quickly jump to a particular part of a code-block's output.

Thanks again!

**Comment by ian-r-rose** [comment]
Ah, good point. I had not considered markdown in outputs. That should be doable.

**Comment by ian-r-rose** [comment]
Hi @kenjioman, I just published v0.2.1 of this extension, which includes support for parsing cell outputs for headers.

**Comment by kenjioman** [comment]
Great!  I'll try updating, and let you know if I have any issues!! Also, awesome response time :)

**Comment by kenjioman** [comment]
I just updated/ checked with my notebook, and things seem to be working fine!  Once again, thank you for your help and for the awesome extension!
