### ISSUE TITLE
How to install extension in home directory?

### ISSUE THREAD

**Issue by goerz** [ian-r-rose/jupyterlab-toc#17]
goerz@mlhpc2:~> /home/goerz/.conda/envs/default/bin/jupyter labextension install jupyterlab-toc
    PermissionError: [Errno 13] Permission denied: '/usr/local/anaconda/share/jupyter/lab/extensions'

Is there any way to install the extension in my home directory?

**Comment by ian-r-rose** [comment]
It should be installed to the same directory that is listed when you run `jupyter lab path`. If you are using conda I would expect it to already be in a user install. Is there a reason that you have specified `/home/goerz/.conda/envs/default/bin/jupyter`, rather than the one in your current environment?

**Comment by goerz** [comment]
Ah, yes, I just found https://github.com/jupyterlab/jupyterlab/issues/4064#issuecomment-369391179 which provides the workaround.

Specifically, I had to do the following:
* Copy the `/usr/local/anaconda/share/jupyter/lab/` to `~/.local/share/jupyter/lab`
* Add `export JUPYTERLAB_DIR=$HOME/.local/share/jupyter/lab` to my `.bashrc`

This got me at least a step further:

~~~
goerz@mlhpc2:~> jupyter labextension install jupyterlab-toc
> /usr/bin/npm pack jupyterlab-toc
jupyterlab-toc-0.2.1.tgz
> node /home/goerz/.conda/envs/default/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.5.1
warning You are using Node "4.2.6" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0"
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
error uglifyjs-webpack-plugin@1.1.8: The engine "node" is incompatible with this module. Expected version ">= 4.8 < 5.0.0 || >= 5.10".
error An unexpected error occurred: "Found incompatible module".
info If you think this is a bug, please open a bug report with the information provided in "/home/goerz/.local/share/jupyter/lab/staging/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> node /home/goerz/.conda/envs/default/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.5.1
warning You are using Node "4.2.6" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0"
$ webpack --config webpack.prod.config.js
sh: 1: webpack: not found
error An unexpected error occurred: "Command failed.
Exit code: 127
Command: sh
Arguments: -c webpack --config webpack.prod.config.js
Directory: /home/goerz/.local/share/jupyter/lab/staging
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/goerz/.local/share/jupyter/lab/staging/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
~~~

Do you think the problem is simply the version of Node that the installation warns about? If so, I'll have to figure out how to update that...

`/home/goerz/.conda/envs/default/bin/jupyter` actually is the current `jupyter`, I just wrote out the full path to make sure it wouldn't get confused by the the "system" `/usr/local/anaconda/bin/jupyter`.

**Comment by ian-r-rose** [comment]
Yes, I expect that version of node to be a problem. I think you will want to install at least node v6.

It looks to me like your environment *was* getting confused about the different `jupyter`s, since it was trying to install into the system one rather than your user one.

**Comment by goerz** [comment]
Ok, I think I got it working. Thanks!

Took me a while to find https://github.com/jupyterlab/jupyterlab/blob/master/CONTRIBUTING.md that points out you can install nodejs in your home directory via conda!

I'll close this issue for now, but it might be good to add a few lines to the README explaining some of these tricks. I imagine installing jupyter on a server without root access is somewhat common in the scientific computing space.
