### ISSUE TITLE
Full markdown/html support

### ISSUE THREAD

**Issue by jfbercher** [ian-r-rose/jupyterlab-toc#3]
Though I haven't tested it in real life, from what I see in the source, I suspect that the headings are detected from the lines beginning by \#. In such case, only the first line in 
![capture du 2018-03-14 18-29-35](https://user-images.githubusercontent.com/7596356/37420684-a69611ac-27b7-11e8-9543-73a892f50f55.png)
will be used in the toc, despite the orther forms should. Perhaps use the jquery `.find(:header)` for rendered cells to get the info.

**Comment by ian-r-rose** [comment]
Good point. I'd prefer to keep working with the text, rather than the rendered HTML, since it will then work with unrendered documents (or things like LaTeX).  I wonder how easy it would be to cook up something to parse the second case.

**Comment by ian-r-rose** [comment]
@jfbercher What do you think about the proposed fix in #4? It adds additional parsing for underline and HTML style headers. The HTML one is incomplete, as it would miss multiline headers, and multiple headers per line, but I think it should capture a lot of cases.

**Comment by jfbercher** [comment]
It seems fine and well done :+1:
