### ISSUE TITLE
NodeJs 5+ error when installing jupyterlab-toc

### ISSUE THREAD

**Issue by pluviosilla** [ian-r-rose/jupyterlab-toc#5]
This error may well look as mysterious to you as it does to me, but I'll post it just in case someone might be able to clue me in.

```
> jupyter labextension install jupyterlab-toc

Errored, use --debug for full output:
ValueError: Please install nodejs 5+ and npm before continuing. nodejs may be installed using conda or directly from the nodejs website.
```

Many of us a delighted you did this (THANKS!). Do you have any plans to add conda support?

**Comment by pluviosilla** [comment]
Never mind. Installing nodejs with 

`conda install nodejs`

fixed the problem. I'm still getting a few errors, notably:

- jupyter\lab\staging\node_modules\canvas: Command failed
- Your current version of Yarn is out of date

**Comment by ian-r-rose** [comment]
Glad you got it worked out. Yes, JupyterLab requires nodejs to install extensions. The canvas error can be safely ignored, and our version of yarn will be updated in the next release.

**Comment by GrigoriiTarasov** [comment]
When i use command 

jupyter labextension install @jupyterlab/toc

I get 

> Node v8.0.0
> 
> 
> Errored, use --debug for full output:
> PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter/lab/extensions'

But when I use 

sudo jupyter labextension install @jupyterlab/toc

I got

> Errored, use --debug for full output:
> ValueError: Please install nodejs >=6.11.5 before continuing. nodejs may be installed using conda or directly from the nodejs website.

**Comment by adejonghm** [comment]
Hi everyone, 
How do I solve this problem if I'm not using conda, I'm using pip.

Any suggestion??

**Comment by BarRozenman** [comment]
maybe "pip install nodejs"

**Comment by BarRozenman** [comment]
try "pip install nodejs"

**Comment by BornRiot** [comment]
@pluviosilla Thank you so much!!! I was having an issue with trying to install Kite for Jupyter Notebook and tried to use a standalone installation of Node.js and that did not work
