### ISSUE TITLE
Last File content stays in the tab

### ISSUE THREAD

**Issue by mocquin** [ian-r-rose/jupyterlab-toc#6]
Hi @ian-r-rose,

first thanks a lot for this great toc2-like extension, I'm really enjoying it and looking forward this project.

I noticed that after I close all my tabs, the content of the last file I used is still in the "Content" tab. It is not really an issue, but probably not an intended behaviour.

Cheers

**Comment by ian-r-rose** [comment]
Yep, you are right @mocquin, thanks for the report!
