### ISSUE TITLE
Multiple heading in same cell

### ISSUE THREAD

**Issue by mocquin** [ian-r-rose/jupyterlab-toc#8]
Hi,

I noticed that if I have multiple markdown headings in the same cell, all the headings are indeed in the toc, but they all take me to the top of that cell. 
Maybe if multiple headings are in the same cell, the links in the toc should bring you to that heading, and not to the top of the cell of that heading ?

**Comment by ian-r-rose** [comment]
There are some unresolved issues that make addressing this a challenge.

1. We could try to scroll to the auto-generated heading anchors in the markdown. However, this pretty quickly runs into difficulties if you have duplicate headers, or two notebooks open at the same time with duplicate headers (see the lengthy discussion in jupyterlab/jupyterlab#1932). This is kind of an unsolved problem within JupyterLab at the moment.
2. We could do a similar thing that is done with the markdown file ToC: Unrender the cell, and scroll the editor cursor to the header location.
3. We could take a somewhat hybrid approach, something like
    * if the cell is rendered, scroll to the top of the cell.
    * if the cell is unrendered, scroll the cursor to the right place.

What do you think?

**Comment by mocquin** [comment]
Well I'm not sure about what I prefer.

I'm not I understand all the insights of the issue within jupyterlab, but I get the point.

I'm not really convinced about the second option because half the time I want to go to a markdown heading is to review/read the rendered-markdown (the other half being to edit it), so I'm not sure I want it to un-render (knowing that if I render it again, I will be taken to the end of the cell).

I basically never let a markdown cell unrendered (unless I'm currently working on it - once I consider it to be neat, I render it and move on), so the third option wouldn't make much difference for my specific personnal usage. But I guess if a cell is unrendered, we might as well be taken to the right place instead of the top of the cell (makes more sense).

**Comment by ian-r-rose** [comment]
I would also prefer not to un-render a cell. It's just that the logic for scrolling to the right heading is more complex in the rendered state. I think it is ultimately the wrong approach to use header anchors, but a function to find the right header element and scroll it into view would not be *too* complicated.
